// Auto-generated by PlatformIO - DO NOT EDIT
#ifndef VERSION_H
#define VERSION_H

#define GIT_HASH "77046c70"
#define GIT_BRANCH "master"
#define BUILD_TIME "2026-02-23 09:05:35"
#define VERSION_STRING "master-77046c70"

#endif
