import os
import subprocess
import datetime

project_dir = os.getcwd()

try:
    git_hash = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], text=True, cwd=project_dir
    ).strip()[:8]
    git_branch = subprocess.check_output(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"], text=True, cwd=project_dir
    ).strip()
except:
    git_hash = "0000000"
    git_branch = "unknown"

now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

version_h = f"""// Auto-generated by PlatformIO - DO NOT EDIT
#ifndef VERSION_H
#define VERSION_H

#define GIT_HASH "{git_hash}"
#define GIT_BRANCH "{git_branch}"
#define BUILD_TIME "{now}"
#define VERSION_STRING "{git_branch}-{git_hash}"

#endif
"""

include_dir = os.path.join(project_dir, "include")
os.makedirs(include_dir, exist_ok=True)
version_path = os.path.join(include_dir, "version.h")
with open(version_path, "w") as f:
    f.write(version_h)

print("Generated version.h: %s-%s" % (git_branch, git_hash))
