// Auto-generated by PlatformIO - DO NOT EDIT
#ifndef VERSION_H
#define VERSION_H

#define GIT_HASH "77046c70"
#define GIT_BRANCH "master"
#define BUILD_TIME "20260223-085548"
#define VERSION_STRING "master-77046c70"

#endif
