; PlatformIO Project Configuration File for Matter
;
; Matter requires ESP32 Arduino core 3.x
; Uses pioarduino fork for PlatformIO support

[platformio]
default_envs = esp32usb

[common]
hostname    = esp32_21
fqdn        = ${common.hostname}.local
platform    = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.12/platform-espressif32.zip
board       = esp32dev
framework   = arduino
board_build.partitions = min_spiffs.csv
build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DHOSTNAME=\"${common.hostname}\"
    -DCHIP_HAVE_CONFIG_H
    -DUSE_TPL_MATTER
    -DNO_NET_WATCHDOG
lib_deps =
    bblanchon/ArduinoJson@^6.17.2
    549@^2.2.1
extra_scripts =
	pre:../prj_template/tools/generate_version.py

[env:esp32ota]
platform    = ${common.platform}
board       = ${common.board}
framework   = ${common.framework}
build_flags = ${common.build_flags}
extra_scripts = ${common.extra_scripts}
lib_deps = ${common.lib_deps}
board_build.partitions = ${common.board_build.partitions}

upload_protocol = espota
upload_port = ${common.fqdn}
upload_flags = --port=3232

[env:esp32usb]
platform    = ${common.platform}
board       = ${common.board}
framework   = ${common.framework}
build_flags = ${common.build_flags}
extra_scripts = ${common.extra_scripts}
lib_deps = ${common.lib_deps}
board_build.partitions = ${common.board_build.partitions}

monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyUSB0
