[platformio]
default_envs = esp32ota
src_dir = .
data_dir = data

[common]
hostname    = esp32_24
fqdn        = ${common.hostname}.local
platform    = espressif32 @ 6.13.0
board       = esp32dev
framework   = arduino
platform_packages =
board_build.f_cpu = 240000000L
board_build.partitions = min_spiffs.csv
build_flags =
	-I include
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-D USER_SETUP_LOADED
	-D ST7789_2_DRIVER
	-D TFT_WIDTH=135
	-D TFT_HEIGHT=240
	-D TFT_MOSI=19
	-D TFT_SCLK=18
	-D TFT_CS=5
	-D TFT_DC=16
	-D TFT_RST=-1
	-D TFT_BL=4
	-D TFT_BACKLIGHT_ON=HIGH
	-D LOAD_GLCD=1
	-D LOAD_FONT2
	-D LOAD_FONT4
	-D LOAD_FONT6
	-D LOAD_FONT7
	-D LOAD_FONT8
	-D LOAD_GFXFF
	-D SMOOTH_FONT
	-D TOUCH_CS=0
	-D SPI_FREQUENCY=40000000
	-D SPI_READ_FREQUENCY=20000000
	-DCORE_DEBUG_LEVEL=1
	-DHOSTNAME=\"${common.hostname}\"
	-DNET_WATCHDOG=\"192.168.1.1\"
lib_deps =
	lvgl/lvgl@^9.1.0
	bodmer/TFT_eSPI@^2.5.43
	bblanchon/ArduinoJson@^6.17.2
	549@^2.2.1
extra_scripts =
	pre:../prj_template/tools/generate_version.py

[env:esp32ota]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
platform_packages = ${common.platform_packages}
build_flags = ${common.build_flags}
extra_scripts = ${common.extra_scripts}
lib_deps =
	${common.lib_deps}
board_build.f_cpu = ${common.board_build.f_cpu}
board_build.partitions = ${common.board_build.partitions}
upload_protocol = espota
upload_port = ${common.fqdn}
upload_flags =
	--port=3232
	--host_port=56789

[env:esp32usb]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
platform_packages = ${common.platform_packages}
build_flags = ${common.build_flags}
extra_scripts = ${common.extra_scripts}
lib_deps =
	${common.lib_deps}
board_build.f_cpu = ${common.board_build.f_cpu}
board_build.partitions = ${common.board_build.partitions}
monitor_speed = 115200
upload_speed = 460800
upload_port = /dev/tty.usbserial-5B340463051
